# Generated by Django 3.2.8 on 2021-10-27 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('mobile1', models.IntegerField(default='', max_length=10)),
                ('mobile2', models.IntegerField(default='', max_length=10)),
                ('email', models.CharField(default='', max_length=30)),
                ('gender', models.CharField(default='', max_length=10)),
                ('age', models.IntegerField(default='', max_length=2)),
                ('dateOfBirth', models.DateField()),
                ('address', models.CharField(default='', max_length=100)),
                ('joinDate', models.IntegerField(default='', max_length=100)),
                ('lastUpdated', models.DateField()),
                ('adharCard', models.ImageField(default='', upload_to='')),
                ('panCard', models.ImageField(default='', upload_to='')),
                ('tenthResult', models.ImageField(default='', upload_to='')),
                ('twelthResult', models.ImageField(default='', upload_to='')),
                ('offerLetter', models.ImageField(default='', upload_to='')),
                ('workingLoc', models.CharField(default='', max_length=30)),
                ('salary', models.IntegerField(default='', max_length=5)),
                ('device', models.CharField(default='', max_length=30)),
                ('maratialStatus', models.CharField(default='', max_length=30)),
                ('department', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('desc', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('module', models.CharField(default='', max_length=30)),
                ('name', models.CharField(default='', max_length=50)),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.role')),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(default='', max_length=50)),
                ('userPassword', models.CharField(default='', max_length=50)),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.role')),
            ],
        ),
    ]
