# Generated by Django 3.2.8 on 2021-10-29 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='joinDate',
            field=models.DateField(),
        ),
    ]
