# Generated by Django 3.2.8 on 2021-10-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_alter_employee_joindate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='adharCard',
            field=models.ImageField(default='', upload_to='accounts/images'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='offerLetter',
            field=models.ImageField(default='', upload_to='accounts/images'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='panCard',
            field=models.ImageField(default='', upload_to='accounts/images'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tenthResult',
            field=models.ImageField(default='', upload_to='accounts/images'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='twelthResult',
            field=models.ImageField(default='', upload_to='accounts/images'),
        ),
    ]
