# Generated by Django 3.2.8 on 2021-10-30 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_auto_20211029_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='firstName',
        ),
        migrations.AddField(
            model_name='employee',
            name='lastName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='middleName',
            field=models.CharField(default='', max_length=50),
        ),
    ]
